# keypair: pk-aws
# security_group: ssh-access
# instance_type: t2.micro
# ami: ami-d732f0b7
# vpc_subnet_id: subnet-3ccdfc58
# region: us-west-2
# instance_tags: {"Name": "ansilbe-built"}
# root_ebs_size: 8
# zone: us-west-2b
# instance_profile_name: mypoweruser
# num_instances: 1
