user_home: /home/ubuntu
django_home: "{{ user_home }}/checkout"
venv_home: "{{ user_home }}/venv"
rds_db_instance: imagerdb
system_packages:
  - build-essential
  - python-dev
  - python-pip
  - postgresql-client
  - libpq-dev
  - python-psycopg2
  - git
  - python-virtualenv
  - libjpeg-dev
  - libtiff-dev
  - libjpeg8-dev
  - zlib1g-dev
  - libfreetype6-dev
  - liblcms2-dev
  - libwebp-dev
  - tcl8.6-dev
  - tk8.6-dev

repo_version: master
django_settings: imagersite.imagersite.settings
