---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items: "{{ system_packages }}"

- name: Clone Django Repository
  git: repo=https://github.com/ilikesounds/django-imager.git 
    dest={{ django_home }}
    force=yes depth=1
    verision = {{ repo_version }}

- name: Install Python Dependencies
  pip:
    virtualenv: "{{ venv_home }}"
    state: present
    requirements: "{{ django_home }}/requirements.txt"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Set DB URL
  set_fact: 
    db_url: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

# - name: Run Migrations
#   environment:
#     DATABASE_URL: "{{ db_url }}"
#   django_manage:
#     app_path: "{{ django_home }}"
#     settings: "{{ django_settings }}"
#     command: migrate

# - name: Collect Static Files
#   environment:
#     DATABASE_URL: "{{ db_url }}"
#   django_manage:
#     app_path: "{{ django_home }}"
#     settings: mysite.production
#     command: collectstatic
