---

# Basic psql provisioning example
- rds:
    command: create
    instance_name: 
    db_engine: MySQL
    size: 10
    instance_type: db.m1.small
    username: mysql_admin
    password: 1nsecure
    tags:
      Environment: testing
      Application: cms